import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    absolute: '',// use it in other page. Which will remove the template suffix. Only show the metadata we give eg: Blog.
    default: 'Next.js tutorial',// this will be the title for all routes which dosen't specify any metadata.
    template: '%s | Codevolution'// this will give a sufix after the title you give in pages. eg: Blog | Codevolution.
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-[100vh]" >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        <div className=" p-5 flex flex-col items-center">
          {children}
        </div>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
        </div>
      </body>
    </html>
  );
}
